# FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
# WORKDIR /app

# NOTE: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user
# USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
# WORKDIR /src
# COPY ["asa-helper-action.csproj", "./"]

COPY . .
RUN dotnet restore "asa-helper-action.csproj"
# WORKDIR "/src/."
RUN dotnet build "asa-helper-action.csproj" -c $configuration -o /app/build

# FROM build AS publish
# ARG configuration=Release
RUN dotnet publish "asa-helper-action.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

# FROM base AS final
# WORKDIR /app
# COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/publish/asa-helper-action.dll"]


